title: TRK Water Start Machine
description: A machine that raises the cable so that the racers can approach and line up
theme: just-the-docs

url: https://water-start-machine.trk.in.rs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
